version: '3.9'
name: finance-tracker

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8887:8887"
    env_file:
      - .env.docker
    depends_on:
      - db
  db:
    image: postgres:16
    container_name: wallets-db
    ports:
      - "${PG_PORT:-5432}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env.docker

volumes:
  db-data:


