version: '3.9'
name: finance-tracker

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8887:8888"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${PG_HOST}:${PG_PORT}/${PG_DB}
      SPRING_DATASOURCE_USERNAME: ${PG_USER}
      SPRING_DATASOURCE_PASSWORD: ${PG_PASSWORD}
    env_file:
      - .env.docker
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: wallets-db
    restart: always
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    env_file:
      - .env.docker

volumes:
  db-data:


