#server:
#  port: 6666

spring:
  application:
    name: template
  datasource:
    url: jdbc:postgresql://localhost:5431/wallets-db
    username: postgres
    password: 12345
  flyway:
    url: jdbc:postgresql://localhost:5431/wallets-db
    user: postgres
    password: 12345
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public
    validate-migration-naming: true
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
