CREATE TABLE expenses
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount DECIMAL NOT NULL,
    time_added DATE NOT NULL,
    category_id BIGINT NOT NULL,
    wallet_id BIGINT NOT NULL,
    FOREIGN KEY (category_id) REFERENCES categories (id)
);