CREATE TABLE transactions
(
   id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
   time_added TIMESTAMP NOT NULL,
   category_id BIGINT,
   amount DECIMAL NOT NULL,
   wallet_id BIGINT NOT NULL,
   operation_type VARCHAR(255)
)