CREATE TABLE transactions
(
   id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   time_added TIMESTAMP,
   start_date DATE,
   last_date DATE,
   category_id BIGINT,
   amount DECIMAL,
   wallet_id BIGINT,
   operation_type VARCHAR(255)
)